# Generated by Django 6.0.2 on 2026-02-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
